name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Stash local changes and pull latest code
      run: |
        cd /var/www/html/LoginFE
        git stash || true
        git pull origin main
        git stash pop || true

    - name: Build Angular project
      run: |
        cd /var/www/html/LoginFE
        npx ng build --configuration production

    - name: Restart Nginx
      run: |
        sudo systemctl restart nginx
