name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Node.js
      run: |
        nvm use 20.14.0
        node -v
        npm -v
    - name: pull latest code
      run: |
        cd /var/www/html/LoginFE
        git pull origin main

    - name: Build Angular project
      run: |
        cd /var/www/html/LoginFE
        ng build 
